version: '3'

networks:
  nginxproxy:
    external: true

services:

  dc-car:
    image: dc-car
    container_name: dc-car
    volumes:
      - ../:/build
    environment:
      - VIRTUAL_HOST=${HOST}
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    restart: always
    logging:
      driver: gcplogs
    networks:
      - nginxproxy
